/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.k7a2;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class K7a2ModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();

	public K7a2ModElements() {
		sounds.put(new ResourceLocation("k7a2", "flashmobcbh"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "flashmobcbh")));
		sounds.put(new ResourceLocation("k7a2", "florentino"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "florentino")));
		sounds.put(new ResourceLocation("k7a2", "magaming"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "magaming")));
		sounds.put(new ResourceLocation("k7a2", "thienlyoi"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "thienlyoi")));
		sounds.put(new ResourceLocation("k7a2", "ifiamwithyou"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "ifiamwithyou")));
		sounds.put(new ResourceLocation("k7a2", "smurfcat"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "smurfcat")));
		sounds.put(new ResourceLocation("k7a2", "dangminh"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "dangminh")));
		sounds.put(new ResourceLocation("k7a2", "danh"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "danh")));
		sounds.put(new ResourceLocation("k7a2", "dat"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "dat")));
		sounds.put(new ResourceLocation("k7a2", "diep"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "diep")));
		sounds.put(new ResourceLocation("k7a2", "duong"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "duong")));
		sounds.put(new ResourceLocation("k7a2", "ducanh"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "ducanh")));
		sounds.put(new ResourceLocation("k7a2", "duongminh"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "duongminh")));
		sounds.put(new ResourceLocation("k7a2", "hai"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "hai")));
		sounds.put(new ResourceLocation("k7a2", "haminh"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "haminh")));
		sounds.put(new ResourceLocation("k7a2", "hoaian"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "hoaian")));
		sounds.put(new ResourceLocation("k7a2", "khanh"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "khanh")));
		sounds.put(new ResourceLocation("k7a2", "khanhs"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "khanhs")));
		sounds.put(new ResourceLocation("k7a2", "kieuthao"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "kieuthao")));
		sounds.put(new ResourceLocation("k7a2", "lam"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "lam")));
		sounds.put(new ResourceLocation("k7a2", "myan"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "myan")));
		sounds.put(new ResourceLocation("k7a2", "ngan"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "ngan")));
		sounds.put(new ResourceLocation("k7a2", "nguyenminh"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "nguyenminh")));
		sounds.put(new ResourceLocation("k7a2", "nguyenphuc"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "nguyenphuc")));
		sounds.put(new ResourceLocation("k7a2", "nhatminh"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "nhatminh")));
		sounds.put(new ResourceLocation("k7a2", "nplinh"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "nplinh")));
		sounds.put(new ResourceLocation("k7a2", "phuong"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "phuong")));
		sounds.put(new ResourceLocation("k7a2", "quynh"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "quynh")));
		sounds.put(new ResourceLocation("k7a2", "tai"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "tai")));
		sounds.put(new ResourceLocation("k7a2", "thai"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "thai")));
		sounds.put(new ResourceLocation("k7a2", "thlinh"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "thlinh")));
		sounds.put(new ResourceLocation("k7a2", "tplinh"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "tplinh")));
		sounds.put(new ResourceLocation("k7a2", "uyen"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "uyen")));
		sounds.put(new ResourceLocation("k7a2", "vhlinh"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "vhlinh")));
		sounds.put(new ResourceLocation("k7a2", "vuthao"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "vuthao")));
		sounds.put(new ResourceLocation("k7a2", "k7a2_mixed_voice"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "k7a2_mixed_voice")));
		sounds.put(new ResourceLocation("k7a2", "endermanhackwin10s"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "endermanhackwin10s")));
		sounds.put(new ResourceLocation("k7a2", "endermansecret"), new net.minecraft.util.SoundEvent(new ResourceLocation("k7a2", "endermansecret")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("k7a2").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == K7a2ModElements.ModElement.class)
						elements.add((K7a2ModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(K7a2ModElements.ModElement::initElements);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	private int messageID = 0;

	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		K7a2Mod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}

	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}

		protected final K7a2ModElements elements;
		protected final int sortid;

		public ModElement(K7a2ModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
